### ISSUE TITLE
OTA not working

### ISSUE THREAD

**Issue by snazzypants** [Brewskey/spark-server#145]
So we've been doing OTA updates pretty routinely over the past few weeks, and all has been working great. Today, the OTA stopped working (times out) and I don't see a reason why that would have happened overnight. We haven't pulled the latest update for the db yet. I've restarted the server which didn't help. Also tried flashing an older version of the firmware that that did not work either.

Here's a snippet from the error logs
```
2017-05-21 21:32 +00:00: (node:23436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Request timed out
2017-05-21 21:34 +00:00: This client has an exclusive lock { cache_key: '_3',
  deviceID: '25001c001547343231323438',
  messageName: undefined }
2017-05-21 21:34 +00:00: (node:23436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Request timed out
2017-05-21 21:36 +00:00: This client has an exclusive lock { cache_key: '_5',
  deviceID: '25001c001547343231323438',
  messageName: undefined }
2017-05-21 21:36 +00:00: (node:23436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: Request timed out
2017-05-21 21:48 +00:00: This client has an exclusive lock { cache_key: '_2',
  deviceID: '25001c001547343231323438',
  messageName: undefined }
2017-05-21 21:48 +00:00: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Request timed out
    at Timeout._onTimeout (/root/node_modules/spark-server/node_modules/spark-protocol/dist/clients/Device.js:494:28)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2017-05-21 21:51 +00:00: (node:1340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Request timed out
2017-05-21 21:54 +00:00: (node:1340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Request timed out
2017-05-21 21:56 +00:00: (node:1340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Request timed out
2017-05-21 22:02 +00:00: This client has an exclusive lock { cache_key: '_3',
  deviceID: '25001c001547343231323438',
  messageName: 'PingAck' }
2017-05-21 22:02 +00:00: This client has an exclusive lock.
2017-05-21 22:03 +00:00: (node:1340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Request timed out
2017-05-21 22:05 +00:00: (node:1340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Request timed out
2017-05-21 22:07 +00:00: (node:1340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: Request timed out
2017-05-21 22:09 +00:00: This client has an exclusive lock { cache_key: '_10',
  deviceID: '25001c001547343231323438',
  messageName: undefined }
2017-05-21 22:09 +00:00: (node:1340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: Request timed out
```

**Comment by jlkalberer** [comment]
Have you pulled recently? I want to make sure it doesn't have to do with the new database code we've added.

**Comment by jlkalberer** [comment]
Try running `node ./node_modules/spark-protocol/dist/scripts/update-firmware-binaries` from the root folder.

I don't have a great idea why it's not working but that is a first step.  I'll try debugging this tomorrow.

**Comment by snazzypants** [comment]
Tried running that script as instructed and still no luck.  Here's the output when trying to OTA, might be more helpful than the previous dump (that one was just a snippet from the error logs). Thanks for looking into this.

On a side note, is there a folder where we can place a binary on the server that would automatically push out the firmware to connected devices - and would that work differently than flashing the firmware from the particle CLI?

```
flash device started! - sending api event { deviceID: '25001c001547343231323438'                                                                             }
fast ota enabled!  { cache_key: '_1', deviceID: '25001c001547343231323438' }
fast ota enabled!  { cache_key: '_1', deviceID: '25001c001547343231323438' }
fast ota enabled!  { cache_key: '_1', deviceID: '25001c001547343231323438' }
releasing flash ownership  { deviceID: '25001c001547343231323438' }
flash device failed! - sending api event { deviceID: '25001c001547343231323438',
  error:
   Error: Request timed out
       at Timeout._onTimeout (/root/node_modules/spark-server/node_modules/spark-protocol/dist/clients/Device.js:494:28)
       at ontimeout (timers.js:365:14)
       at tryOnTimeout (timers.js:237:5)
       at Timer.listOnTimeout (timers.js:207:5) }
::ffff:76.126.13.74 - - [22/May/2017:04:54:56 +0000] "PUT /v1/devices/25001c001547343231323438?access_token=xxxxxxx HTTP/1.1" 400 55 "-" "-"
(node:21936) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Request timed out
1 : Device disconnected: socket timeout { cache_key: '_1',
  deviceID: '25001c001547343231323438',
  duration: 84.408 }
Session ended for device with ID: 25001c001547343231323438 with connectionKey: _1
```

**Comment by snazzypants** [comment]
OK, maybe a false alarm. It's a little unclear exactly what the issue was because we had tried/changed so many things in the course of troubleshooting.  But we think it was related to the last version of our firmware essentially bricking future updates, and potentially some weirdness with compiling the new firmware.

Thanks for your quick response!

**Comment by jlkalberer** [comment]
Yeah.. that's what the error looked like :)
