### ISSUE TITLE
Not working with npm 5.x

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#172]
I'm working on a DockerImage for these wonderfull work.
Right now the Image is not working with NPM 5.x (current version in Alpine-Node) installed

Installation is working as expected, but startup ends with 

`module.js:487
    throw err;
    ^

Error: Cannot find module 'h5.coap'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/localCloud/spark-server/node_modules/spark-protocol/dist/clients/Device.js:48:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/localCloud/spark-server/node_modules/spark-protocol/dist/server/DeviceServer.js:63:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/localCloud/spark-server/node_modules/spark-protocol/dist/index.js:24:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/localCloud/spark-server/dist/defaultBindings.js:19:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

So keep this in mind when you ugrade your node/npm

**Comment by jlkalberer** [comment]
Yeah, NPM 5 has been giving us a lot of issues :(

**Comment by haeferer** [comment]
Yep, as far as 
i understand this seems to be a dependency to a libary which is not published
in NPM (h5.coap). It's included using GIT by spark-protocol
If you add this libary manualy you will get another error (about a missing ErrorClass)
maybe there is also a broken dependecie...
