### ISSUE TITLE
Running Tests on pre-commit requires sudo on MAC

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#200]
Currenty i cant commit to repository, cause to test (configured as pre-commit) fails with 
(on MACOS), so commit fails also...

```
Uncaught Exception: test/DeviceClaimsController.test.js
  Error: EACCES: permission denied, mkdir '/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/.cache'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at sync (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/mkdirp/index.js:77:24)
    at transform (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/caching-transform/index.js:36:12)
    at CachingPrecompiler.transform (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/caching-transform/index.js:60:17)
    at CachingPrecompiler.precompileFile (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/lib/caching-precompiler.js:35:8)
    at Api._runFile (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/api.js:68:30)
    at Promise.catch.err.results (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/api.js:250:21)
    at /Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/api.js:248:11
From previous event:
    at Api._runWithoutPool (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/api.js:247:4)
    at Api._run (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/api.js:170:20)
    at /Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/api.js:88:16
From previous event:
    at Api.run (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/api.js:87:4)
    at Object.exports.run (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/lib/cli.js:159:7)
    at Object.<anonymous> (/Users/haeferer/Desktop/RemoteReps/keatec/spark-server/node_modules/ava/cli.js:23:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by AntonPuko** [comment]
This seems something with your internal access rights for ./node_modules/.cache folder.
try `sudo chown -R $USER:$GROUP ~/.cache` or something like that

**Comment by AntonPuko** [comment]
ah... try to delete __test_data__/db folder before running tests, since we added neDb yesterday and it makes changes in append mode, it doesn't clean the folder in right way.

**Comment by haeferer** [comment]
If you commit you need Sudo rights to run the tests
