### ISSUE TITLE
Spark-Server fails after some time (commit  066f863)

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#202]
Failure log was 

```
1 : Device disconnected: Device was already connected. Reconnecting.
,{"cache_key":"_81","deviceID":"3d004b001051353338363333","duration":290.72}
Session ended for device with ID: 3d004b001051353338363333 with connectionKey: _81
1 : Device disconnected: socket error: read ECONNRESET,{"cache_key":"_82","deviceID":"3d004b001051353338363333","duration":82.449}
Session ended for device with ID: 3d004b001051353338363333 with connectionKey: _82
1 : Device disconnected: socket close,{"cache_key":"_83","deviceID":"3d004b001051353338363333","duration":0.005}
Session ended for device with ID: 3d004b001051353338363333 with connectionKey: _83
uncaughtException,{"message":"Request timed out - Describe","stack":"Error: Request timed out - Describe\n    at Timeout._onTimeout (/usr/src/localCloud/spark-server/node_modules/spark-protocol/dist/clients/Device.js:1074:15)\n    at ontimeout (timers.js:386:14)\n    at tryOnTimeout (timers.js:250:5)\n    at Timer.list
OnTimeout (timers.js:214:5)"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spark-server@0.1.1 start:prod: `node ./dist/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spark-server@0.1.1 start:prod script 'node ./dist/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spark-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./dist/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spark-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spark-server
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-16T16_01_44_446Z-debug.log

ahr@tt-wsahr MINGW64 /d/keastick/water/LocalSparc (master)
$
```

**Comment by haeferer** [comment]
Does not happen again
