### ISSUE TITLE
npm install needs to run twice

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#227]
after  git clone into an empty directory, npm install runs without errors

if you run npm install again you will get (on MacOS)

```
└─┬ bunyan@1.8.10
  └─┬ mv@2.1.1
    └─┬ rimraf@2.4.5 
      └── glob@6.0.4 
```

I dont know if this is a problem, but it looks strange to me

Also it doesnt start (maybe this is again a problem with install on MacOS)

````
$ node ./dist/main
/Users/.../Desktop/vscode/spark-server/node_modules/spark-protocol/dist/lib/FirmwareManager.js:95
})[0];
  ^

TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (/Users/haeferer/Desktop/vscode/spark-server/node_modules/spark-protocol/dist/lib/FirmwareManager.js:95:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/haeferer/Desktop/vscode/spark-server/node_modules/spark-protocol/dist/server/DeviceServer.js:63:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/haeferer/Desktop/vscode/spark-server/node_modules/spark-protocol/dist/index.js:24:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/haeferer/Desktop/vscode/spark-server/dist/defaultBindings.js:19:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by haeferer** [comment]
is #229
