### ISSUE TITLE
Docker build fails during start

### ISSUE THREAD

**Issue by haeferer** [Brewskey/spark-server#230]
reason: maybe missing third-partie directory

```
> spark-server@0.1.1 start:prod /usr/src/localCloud/spark-server
> node ./dist/main.js

/usr/src/localCloud/spark-server/node_modules/spark-protocol/dist/lib/FirmwareManager.js:95
})[0];
  ^

TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (/usr/src/localCloud/spark-server/node_modules/spark-protocol/dist/lib/FirmwareManager.js:95:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/localCloud/spark-server/node_modules/spark-protocol/dist/server/DeviceServer.js:63:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/localCloud/spark-server/node_modules/spark-protocol/dist/index.js:24:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/localCloud/spark-server/dist/defaultBindings.js:19:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spark-server@0.1.1 start:prod: `node ./dist/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spark-server@0.1.1 start:prod script 'node ./dist/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spark-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./dist/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spark-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spark-server
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-30T06_37_46_059Z-debug.log`
```

**Comment by haeferer** [comment]
is #231
