### ISSUE TITLE
ERROR: DeviceServer.js for local server

### ISSUE THREAD

**Issue by About7Sharks** [Brewskey/spark-server#275]
Photon device successfully flashes firmware.bin but when connecting to the local server I receive this error.

```
[2018-09-04T15:34:26.535Z]  INFO: Device.js/2592 on AccuBreDev1: On device protocol initialization complete (cache_key=_11, deviceID=2f003b001047363333343437, firmwareVersion=65535, ip=::ffff:10.10.10.10, particleProductId=6, platformId=6)
[2018-09-04T15:34:26.546Z] ERROR: DeviceServer.js/2592 on AccuBreDev1: Error
    TypeError: Cannot read property 'prefixInfo' of undefined
        at _loop (/root/spark-server/node_modules/spark-protocol/dist/lib/FirmwareManager.js:119:49)
        at _callee$ (/root/spark-server/node_modules/spark-protocol/dist/lib/FirmwareManager.js:136:15)
        at tryCatch (/root/spark-server/node_modules/regenerator-runtime/runtime.js:62:40)
        at Generator.invoke [as _invoke] (/root/spark-server/node_modules/regenerator-runtime/runtime.js:296:22)
        at Generator.prototype.(anonymous function) [as next] (/root/spark-server/node_modules/regenerator-runtime/runtime.js:114:21)
        at step (/root/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
        at /root/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
        at new Promise (<anonymous>)
        at new F (/root/spark-server/node_modules/core-js/library/modules/_export.js:36:28)
        at Function.<anonymous> (/root/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
        at Function.getOtaSystemUpdateConfig (/root/spark-server/node_modules/spark-protocol/dist/lib/FirmwareManager.js:175:17)
        at DeviceServer._callee2$ (/root/spark-server/node_modules/spark-protocol/dist/server/DeviceServer.js:141:50)
        at tryCatch (/root/spark-server/node_modules/regenerator-runtime/runtime.js:62:40)
        at Generator.invoke [as _invoke] (/root/spark-server/node_modules/regenerator-runtime/runtime.js:296:22)
        at Generator.prototype.(anonymous function) [as next] (/root/spark-server/node_modules/regenerator-runtime/runtime.js:114:21)
        at step (/root/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
        at /root/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
        at <anonymous>
[2018-09-04T15:34:26.547Z]  INFO: DeviceServer.js/2592 on AccuBreDev1: Subscribe Request (deviceID=2f003b001047363333343437, isFromMyDevices=false, messageName=spark)
[2018-09-04T15:34:27.276Z]  INFO: DeviceServer.js/2592 on AccuBreDev1: Connected Devices (devices=1, sockets=1)
```

**Comment by jlkalberer** [comment]
Have you ran `update-firmwaare` a few times? github will only let you download so many files at once so you may be missing some system firmeware.

**Comment by About7Sharks** [comment]
Everything appears to be working after `particle update` thanks!
