### ISSUE TITLE
update-firmware requests failing

### ISSUE THREAD

**Issue by mrferrar** [Brewskey/spark-server#288]
Hello, when running update-firmware many of the file requests respond with an HTTPerror. The error is an InvalidArgument: 

> Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified

Is my .env file improperly formatted, causing an issue with the auth?

An example of one of the full messages is below:

```
{ url: 'https://api.github.com/repos/particle-iot/firmware/releases/assets/4568911',
  id: 4568911,
  node_id: 'MDEyOlJlbGVhc2VBc3NldDQ1Njg5MTE=',
  name: 'system-part2-0.7.0-rc.3-p1.bin',
  label: null,
  uploader: 
   { login: 'technobly',
     id: 2249224,
     node_id: 'MDQ6VXNlcjIyNDkyMjQ=',
     avatar_url: 'https://avatars2.githubusercontent.com/u/2249224?v=4',
     gravatar_id: '',
     url: 'https://api.github.com/users/technobly',
     html_url: 'https://github.com/technobly',
     followers_url: 'https://api.github.com/users/technobly/followers',
     following_url: 'https://api.github.com/users/technobly/following{/other_user}',
     gists_url: 'https://api.github.com/users/technobly/gists{/gist_id}',
     starred_url: 'https://api.github.com/users/technobly/starred{/owner}{/repo}',
     subscriptions_url: 'https://api.github.com/users/technobly/subscriptions',
     organizations_url: 'https://api.github.com/users/technobly/orgs',
     repos_url: 'https://api.github.com/users/technobly/repos',
     events_url: 'https://api.github.com/users/technobly/events{/privacy}',
     received_events_url: 'https://api.github.com/users/technobly/received_events',
     type: 'User',
     site_admin: false },
  content_type: 'application/macbinary',
  state: 'uploaded',
  size: 255420,
  download_count: 153,
  created_at: '2017-08-14T05:37:20Z',
  updated_at: '2017-08-14T05:37:21Z',
  browser_download_url: 'https://github.com/particle-iot/firmware/releases/download/v0.7.0-rc.3/system-part2-0.7.0-rc.3-p1.bin' } { HttpError: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Only one auth mechanism allowed; only the X-Amz-Algorithm query parameter, Signature query string parameter or the Authorization header should be specified</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Basic bXJmZXJyYXI6VW5jMG5kMXQxMG5hbDs=</ArgumentValue><RequestId>24019758BAC147C8</RequestId><HostId>Fvbna4YfE8XzZrx/lxOSV/SLiZ6bYgwNN0AZ3CnF2qaLWXkUJtLmpLbBkirJ6Y3nglB+1E/WLrI=</HostId></Error>
    at response.text.then.message (/spark/spark-server/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'HttpError',
  code: 400,
  status: 'Bad Request',
  headers: 
   { connection: 'close',
     'content-type': 'application/xml',
     date: 'Thu, 13 Dec 2018 00:19:34 GMT',
     server: 'AmazonS3',
     'transfer-encoding': 'chunked',
     'x-amz-id-2': 'Fvbna4YfE8XzZrx/lxOSV/SLiZ6bYgwNN0AZ3CnF2qaLWXkUJtLmpLbBkirJ6Y3nglB+1E/WLrI=',
     'x-amz-request-id': '24019758BAC147C8' } }

```

**Comment by mrferrar** [comment]
That fixed it, thanks!
