### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Mcurti12** [Brewskey/spark-server#297]
Does anyone know if this still works as listed in the readme? I am not able to set it up so I wanted to see if it was even still active?

**Comment by brahma-dev** [comment]
Yes, it's being used in production.

**Comment by Mcurti12** [comment]
> Yes, it's being used in production.

Thanks for the reply. Would you have any details about any changes needed to get it working today? Or if there are any changes made in the last few years not shown in the readme? Any info would be amazing, thank you.

**Comment by jlkalberer** [comment]
Can you explain what isn't working for you?

I know Particle has made some changes to their CLI that could be causing some issue -- especially if you're trying to use UDP instead of TCP for your connections.

**Comment by Mcurti12** [comment]
So currently the issue I am having is after using the particle cloud login cmd. It gives an error saying it can't log in then "Connect ECONNREFUSED ip address. I am using ip address:8080.

**Comment by Mcurti12** [comment]
I was having issues using the Rpi quick setup guide so I used information from another help forum so I am not sure that is related. I will keep trying different things to get it work. I just wanted to make sure it wasn't completely inactive. Does that issue sound like it could be related to the CLI changes?

**Comment by jlkalberer** [comment]
Are you trying to log in through localhost or are you connecting to the RPi externally?
That error looks like you might have a firewall issue or something with the RPi itself.

I'd search through the issues because I think someone else ran into problems with RPi 

---

Also, you should include as many details as possible when filing issues. Otherwise it's way too much back and forth.

**Comment by Mcurti12** [comment]
Thank you for the help. I will attempt to fix these issues and I will include many more details in my next post.

**Comment by DaliborFarny** [comment]
> Thank you for the help. I will attempt to fix these issues and I will include many more details in my next post.

Start the cloud server and try to access it directly from a browser (not CLI). In your case, just type http://your-server-url.com:8080/ and you should get this reply: "Not Found". If you get this reply, then it works..

**Comment by Mcurti12** [comment]
Thank you for the comments. I was able to set up the server(including getting the not found reply). I am having trouble with the particle setup cmd though. I am getting stuck on the reconnecting your computer to your wi-fi network then it times out. Any advice for this part of the setup? I am using port 8080 for all my setup, I am not using port 5683, is that right? I am trying to connect a Photon to the server. Also, I am using npm for the run start:prod instead of yarn. Is that an issue? Thank you!

**Comment by Mcurti12** [comment]
Thank you for the comments. I was able to set up the server(including getting the not found reply). I am having trouble with the particle setup cmd though. I am getting stuck on the reconnecting your computer to your wi-fi network then it times out. Any advice for this part of the setup? I am using port 8080 for all my setup, I am not using port 5683, is that right? I am trying to connect a Photon to the server. Also, I am using npm for the run start:prod instead of yarn. Is that an issue? Thank you!

**Comment by Mcurti12** [comment]
This is the errors I am getting in the terminal when trying to connect.
 INFO: Device.js/2477 on localcloud: Device disconnected (cache_key=_21, deviceID="", disconnectCounter=1)
[2021-05-26T20:21:48.007Z] ERROR: DeviceServer.js/2477 on localcloud: Device startup failed (deviceID=null)
    Error: handshake data decryption failed. You probably have incorrect server key for device
        at Handshake._callee4$ (/home/localcloud/spark-server/node_modules/spark-protocol/dist/lib/Handshake.js:302:21)
        at tryCatch (/home/localcloud/spark-server/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
        at Generator.invoke [as _invoke] (/home/localcloud/spark-server/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
        at Generator.prototype.(anonymous function) [as next] (/home/localcloud/spark-server/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
        at step (/home/localcloud/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
        at /home/localcloud/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
        at new Promise (<anonymous>)
        at new F (/home/localcloud/spark-server/node_modules/core-js/library/modules/_export.js:36:28)
        at Handshake.<anonymous> (/home/localcloud/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
        at Handshake._readDeviceHandshakeData (/home/localcloud/spark-server/node_modules/spark-protocol/dist/lib/Handshake.js:343:20)
        at Handshake._callee2$ (/home/localcloud/spark-server/node_modules/spark-protocol/dist/lib/Handshake.js:184:26)
        at tryCatch (/home/localcloud/spark-server/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
        at Generator.invoke [as _invoke] (/home/localcloud/spark-server/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
        at Generator.prototype.(anonymous function) [as next] (/home/localcloud/spark-server/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
        at step (/home/localcloud/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
        at /home/localcloud/spark-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
        at process._tickCallback (internal/process/next_tick.js:68:7)
[2021-05-26T20:21:56.468Z]  INFO: DeviceServer.js/2477 on localcloud: Connected Devices (devices=0, sockets=0)

**Comment by brahma-dev** [comment]
It appears you haven't fully setup the device yet. Please follow the readme till the end. The `particle keys` commands.
https://github.com/Brewskey/spark-server#readme

**Comment by Mcurti12** [comment]
> It appears you haven't fully setup the device yet. Please follow the readme till the end. The `particle keys` commands.
> https://github.com/Brewskey/spark-server#readme

Thanks! I ran these command: Do you see anything I did wrong? I tried to follow the readme the best I could. One thing I am a bit confused about is when it says 'Change server keys to local cloud key + IP Address'. Is that something else I need to do or is that what the next command is doing?
particle keys server ./data/default_key.pub.pem --host 192.168.58.93
particle keys doctor core_id

particle keys new test_key --protocol tcp
particle keys load test_key.der
particle keys send core_id test_key.pub.pem

**Comment by brahma-dev** [comment]
You have to replace core_id with the id you got from the identify command. It would be helpful if you can provide the output of the commands.

**Comment by Mcurti12** [comment]
Oh sorry, I did replace core_id with my actual id number I just didn't put it here. I'd be happy to post the output of the commands but all of that did work properly. It just either prompted me for info or confirmed. It's only when I reach the setup stage that I get that handshake error and it won't connect. Sorry if that's not enough info
